services:
  web:
    build:
      dockerfile: Containerfile # needed for Docker compatibility
    environment:
      FLASK_RUN_DEBUG: true
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    command: flask run
