services:
  python:
    build:
      dockerfile: .docker/Dockerfile
    environment:
      FLASK_RUN_DEBUG: "true"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "5000"
    ports:
      - "5000:5000"
    volumes:
      - './:/app'
    entrypoint: /bin/bash -c
    command:
      - flask run
